spring.application.name=Lanmessenger
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
debug=true
# Set the maximum size of a single file to 1000MB (default is 1MB)
spring.servlet.multipart.max-file-size=1000MB
# Set the maximum size of the total request (including multiple files) to 1000MB
spring.servlet.multipart.max-request-size=1000MB
# File Storage Properties
file.upload-dir=./uploads
server.servlet.session.timeout=-1
server.port=6143